#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleRSS.Resource", IsApplication=true)]

namespace SimpleRSS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0500b7
			public const int md_amber_100 = 2131034295;
			
			// aapt resource value: 0x7f0500b8
			public const int md_amber_200 = 2131034296;
			
			// aapt resource value: 0x7f0500b9
			public const int md_amber_300 = 2131034297;
			
			// aapt resource value: 0x7f0500ba
			public const int md_amber_400 = 2131034298;
			
			// aapt resource value: 0x7f0500b6
			public const int md_amber_50 = 2131034294;
			
			// aapt resource value: 0x7f0500bb
			public const int md_amber_500 = 2131034299;
			
			// aapt resource value: 0x7f0500bc
			public const int md_amber_600 = 2131034300;
			
			// aapt resource value: 0x7f0500bd
			public const int md_amber_700 = 2131034301;
			
			// aapt resource value: 0x7f0500be
			public const int md_amber_800 = 2131034302;
			
			// aapt resource value: 0x7f0500bf
			public const int md_amber_900 = 2131034303;
			
			// aapt resource value: 0x7f0500c0
			public const int md_amber_A100 = 2131034304;
			
			// aapt resource value: 0x7f0500c1
			public const int md_amber_A200 = 2131034305;
			
			// aapt resource value: 0x7f0500c2
			public const int md_amber_A400 = 2131034306;
			
			// aapt resource value: 0x7f0500c3
			public const int md_amber_A700 = 2131034307;
			
			// aapt resource value: 0x7f0500f4
			public const int md_black_1000 = 2131034356;
			
			// aapt resource value: 0x7f050047
			public const int md_blue_100 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int md_blue_200 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int md_blue_300 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int md_blue_400 = 2131034186;
			
			// aapt resource value: 0x7f050046
			public const int md_blue_50 = 2131034182;
			
			// aapt resource value: 0x7f05004b
			public const int md_blue_500 = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int md_blue_600 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int md_blue_700 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int md_blue_800 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int md_blue_900 = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int md_blue_A100 = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int md_blue_A200 = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int md_blue_A400 = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int md_blue_A700 = 2131034195;
			
			// aapt resource value: 0x7f0500f7
			public const int md_blue_grey_100 = 2131034359;
			
			// aapt resource value: 0x7f0500f8
			public const int md_blue_grey_200 = 2131034360;
			
			// aapt resource value: 0x7f0500f9
			public const int md_blue_grey_300 = 2131034361;
			
			// aapt resource value: 0x7f0500fa
			public const int md_blue_grey_400 = 2131034362;
			
			// aapt resource value: 0x7f0500f6
			public const int md_blue_grey_50 = 2131034358;
			
			// aapt resource value: 0x7f0500fb
			public const int md_blue_grey_500 = 2131034363;
			
			// aapt resource value: 0x7f0500fc
			public const int md_blue_grey_600 = 2131034364;
			
			// aapt resource value: 0x7f0500fd
			public const int md_blue_grey_700 = 2131034365;
			
			// aapt resource value: 0x7f0500fe
			public const int md_blue_grey_800 = 2131034366;
			
			// aapt resource value: 0x7f0500ff
			public const int md_blue_grey_900 = 2131034367;
			
			// aapt resource value: 0x7f0500e1
			public const int md_brown_100 = 2131034337;
			
			// aapt resource value: 0x7f0500e2
			public const int md_brown_200 = 2131034338;
			
			// aapt resource value: 0x7f0500e3
			public const int md_brown_300 = 2131034339;
			
			// aapt resource value: 0x7f0500e4
			public const int md_brown_400 = 2131034340;
			
			// aapt resource value: 0x7f0500e0
			public const int md_brown_50 = 2131034336;
			
			// aapt resource value: 0x7f0500e5
			public const int md_brown_500 = 2131034341;
			
			// aapt resource value: 0x7f0500e6
			public const int md_brown_600 = 2131034342;
			
			// aapt resource value: 0x7f0500e7
			public const int md_brown_700 = 2131034343;
			
			// aapt resource value: 0x7f0500e8
			public const int md_brown_800 = 2131034344;
			
			// aapt resource value: 0x7f0500e9
			public const int md_brown_900 = 2131034345;
			
			// aapt resource value: 0x7f050063
			public const int md_cyan_100 = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int md_cyan_200 = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int md_cyan_300 = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int md_cyan_400 = 2131034214;
			
			// aapt resource value: 0x7f050062
			public const int md_cyan_50 = 2131034210;
			
			// aapt resource value: 0x7f050067
			public const int md_cyan_500 = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int md_cyan_600 = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int md_cyan_700 = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int md_cyan_800 = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int md_cyan_900 = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int md_cyan_A100 = 2131034220;
			
			// aapt resource value: 0x7f05006d
			public const int md_cyan_A200 = 2131034221;
			
			// aapt resource value: 0x7f05006e
			public const int md_cyan_A400 = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int md_cyan_A700 = 2131034223;
			
			// aapt resource value: 0x7f0500d3
			public const int md_deep_orange_100 = 2131034323;
			
			// aapt resource value: 0x7f0500d4
			public const int md_deep_orange_200 = 2131034324;
			
			// aapt resource value: 0x7f0500d5
			public const int md_deep_orange_300 = 2131034325;
			
			// aapt resource value: 0x7f0500d6
			public const int md_deep_orange_400 = 2131034326;
			
			// aapt resource value: 0x7f0500d2
			public const int md_deep_orange_50 = 2131034322;
			
			// aapt resource value: 0x7f0500d7
			public const int md_deep_orange_500 = 2131034327;
			
			// aapt resource value: 0x7f0500d8
			public const int md_deep_orange_600 = 2131034328;
			
			// aapt resource value: 0x7f0500d9
			public const int md_deep_orange_700 = 2131034329;
			
			// aapt resource value: 0x7f0500da
			public const int md_deep_orange_800 = 2131034330;
			
			// aapt resource value: 0x7f0500db
			public const int md_deep_orange_900 = 2131034331;
			
			// aapt resource value: 0x7f0500dc
			public const int md_deep_orange_A100 = 2131034332;
			
			// aapt resource value: 0x7f0500dd
			public const int md_deep_orange_A200 = 2131034333;
			
			// aapt resource value: 0x7f0500de
			public const int md_deep_orange_A400 = 2131034334;
			
			// aapt resource value: 0x7f0500df
			public const int md_deep_orange_A700 = 2131034335;
			
			// aapt resource value: 0x7f05002b
			public const int md_deep_purple_100 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int md_deep_purple_200 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int md_deep_purple_300 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int md_deep_purple_400 = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int md_deep_purple_50 = 2131034154;
			
			// aapt resource value: 0x7f05002f
			public const int md_deep_purple_500 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int md_deep_purple_600 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int md_deep_purple_700 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int md_deep_purple_800 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int md_deep_purple_900 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int md_deep_purple_A100 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int md_deep_purple_A200 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int md_deep_purple_A400 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int md_deep_purple_A700 = 2131034167;
			
			// aapt resource value: 0x7f05007f
			public const int md_green_100 = 2131034239;
			
			// aapt resource value: 0x7f050080
			public const int md_green_200 = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int md_green_300 = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int md_green_400 = 2131034242;
			
			// aapt resource value: 0x7f05007e
			public const int md_green_50 = 2131034238;
			
			// aapt resource value: 0x7f050083
			public const int md_green_500 = 2131034243;
			
			// aapt resource value: 0x7f050084
			public const int md_green_600 = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int md_green_700 = 2131034245;
			
			// aapt resource value: 0x7f050086
			public const int md_green_800 = 2131034246;
			
			// aapt resource value: 0x7f050087
			public const int md_green_900 = 2131034247;
			
			// aapt resource value: 0x7f050088
			public const int md_green_A100 = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int md_green_A200 = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int md_green_A400 = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int md_green_A700 = 2131034251;
			
			// aapt resource value: 0x7f0500eb
			public const int md_grey_100 = 2131034347;
			
			// aapt resource value: 0x7f0500ec
			public const int md_grey_200 = 2131034348;
			
			// aapt resource value: 0x7f0500ed
			public const int md_grey_300 = 2131034349;
			
			// aapt resource value: 0x7f0500ee
			public const int md_grey_400 = 2131034350;
			
			// aapt resource value: 0x7f0500ea
			public const int md_grey_50 = 2131034346;
			
			// aapt resource value: 0x7f0500ef
			public const int md_grey_500 = 2131034351;
			
			// aapt resource value: 0x7f0500f0
			public const int md_grey_600 = 2131034352;
			
			// aapt resource value: 0x7f0500f1
			public const int md_grey_700 = 2131034353;
			
			// aapt resource value: 0x7f0500f2
			public const int md_grey_800 = 2131034354;
			
			// aapt resource value: 0x7f0500f3
			public const int md_grey_900 = 2131034355;
			
			// aapt resource value: 0x7f050039
			public const int md_indigo_100 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int md_indigo_200 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int md_indigo_300 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int md_indigo_400 = 2131034172;
			
			// aapt resource value: 0x7f050038
			public const int md_indigo_50 = 2131034168;
			
			// aapt resource value: 0x7f05003d
			public const int md_indigo_500 = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int md_indigo_600 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int md_indigo_700 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int md_indigo_800 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int md_indigo_900 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int md_indigo_A100 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int md_indigo_A200 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int md_indigo_A400 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int md_indigo_A700 = 2131034181;
			
			// aapt resource value: 0x7f050055
			public const int md_light_blue_100 = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int md_light_blue_200 = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int md_light_blue_300 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int md_light_blue_400 = 2131034200;
			
			// aapt resource value: 0x7f050054
			public const int md_light_blue_50 = 2131034196;
			
			// aapt resource value: 0x7f050059
			public const int md_light_blue_500 = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int md_light_blue_600 = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int md_light_blue_700 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int md_light_blue_800 = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int md_light_blue_900 = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int md_light_blue_A100 = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int md_light_blue_A200 = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int md_light_blue_A400 = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int md_light_blue_A700 = 2131034209;
			
			// aapt resource value: 0x7f05008d
			public const int md_light_green_100 = 2131034253;
			
			// aapt resource value: 0x7f05008e
			public const int md_light_green_200 = 2131034254;
			
			// aapt resource value: 0x7f05008f
			public const int md_light_green_300 = 2131034255;
			
			// aapt resource value: 0x7f050090
			public const int md_light_green_400 = 2131034256;
			
			// aapt resource value: 0x7f05008c
			public const int md_light_green_50 = 2131034252;
			
			// aapt resource value: 0x7f050091
			public const int md_light_green_500 = 2131034257;
			
			// aapt resource value: 0x7f050092
			public const int md_light_green_600 = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int md_light_green_700 = 2131034259;
			
			// aapt resource value: 0x7f050094
			public const int md_light_green_800 = 2131034260;
			
			// aapt resource value: 0x7f050095
			public const int md_light_green_900 = 2131034261;
			
			// aapt resource value: 0x7f050096
			public const int md_light_green_A100 = 2131034262;
			
			// aapt resource value: 0x7f050097
			public const int md_light_green_A200 = 2131034263;
			
			// aapt resource value: 0x7f050098
			public const int md_light_green_A400 = 2131034264;
			
			// aapt resource value: 0x7f050099
			public const int md_light_green_A700 = 2131034265;
			
			// aapt resource value: 0x7f05009b
			public const int md_lime_100 = 2131034267;
			
			// aapt resource value: 0x7f05009c
			public const int md_lime_200 = 2131034268;
			
			// aapt resource value: 0x7f05009d
			public const int md_lime_300 = 2131034269;
			
			// aapt resource value: 0x7f05009e
			public const int md_lime_400 = 2131034270;
			
			// aapt resource value: 0x7f05009a
			public const int md_lime_50 = 2131034266;
			
			// aapt resource value: 0x7f05009f
			public const int md_lime_500 = 2131034271;
			
			// aapt resource value: 0x7f0500a0
			public const int md_lime_600 = 2131034272;
			
			// aapt resource value: 0x7f0500a1
			public const int md_lime_700 = 2131034273;
			
			// aapt resource value: 0x7f0500a2
			public const int md_lime_800 = 2131034274;
			
			// aapt resource value: 0x7f0500a3
			public const int md_lime_900 = 2131034275;
			
			// aapt resource value: 0x7f0500a4
			public const int md_lime_A100 = 2131034276;
			
			// aapt resource value: 0x7f0500a5
			public const int md_lime_A200 = 2131034277;
			
			// aapt resource value: 0x7f0500a6
			public const int md_lime_A400 = 2131034278;
			
			// aapt resource value: 0x7f0500a7
			public const int md_lime_A700 = 2131034279;
			
			// aapt resource value: 0x7f0500c5
			public const int md_orange_100 = 2131034309;
			
			// aapt resource value: 0x7f0500c6
			public const int md_orange_200 = 2131034310;
			
			// aapt resource value: 0x7f0500c7
			public const int md_orange_300 = 2131034311;
			
			// aapt resource value: 0x7f0500c8
			public const int md_orange_400 = 2131034312;
			
			// aapt resource value: 0x7f0500c4
			public const int md_orange_50 = 2131034308;
			
			// aapt resource value: 0x7f0500c9
			public const int md_orange_500 = 2131034313;
			
			// aapt resource value: 0x7f0500ca
			public const int md_orange_600 = 2131034314;
			
			// aapt resource value: 0x7f0500cb
			public const int md_orange_700 = 2131034315;
			
			// aapt resource value: 0x7f0500cc
			public const int md_orange_800 = 2131034316;
			
			// aapt resource value: 0x7f0500cd
			public const int md_orange_900 = 2131034317;
			
			// aapt resource value: 0x7f0500ce
			public const int md_orange_A100 = 2131034318;
			
			// aapt resource value: 0x7f0500cf
			public const int md_orange_A200 = 2131034319;
			
			// aapt resource value: 0x7f0500d0
			public const int md_orange_A400 = 2131034320;
			
			// aapt resource value: 0x7f0500d1
			public const int md_orange_A700 = 2131034321;
			
			// aapt resource value: 0x7f05000f
			public const int md_pink_100 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int md_pink_200 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int md_pink_300 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int md_pink_400 = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int md_pink_50 = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int md_pink_500 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int md_pink_600 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int md_pink_700 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int md_pink_800 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int md_pink_900 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int md_pink_A100 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int md_pink_A200 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int md_pink_A400 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int md_pink_A700 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int md_purple_100 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int md_purple_200 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int md_purple_300 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int md_purple_400 = 2131034144;
			
			// aapt resource value: 0x7f05001c
			public const int md_purple_50 = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int md_purple_500 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int md_purple_600 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int md_purple_700 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int md_purple_800 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int md_purple_900 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int md_purple_A100 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int md_purple_A200 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int md_purple_A400 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int md_purple_A700 = 2131034153;
			
			// aapt resource value: 0x7f050001
			public const int md_red_100 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int md_red_200 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int md_red_300 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int md_red_400 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int md_red_50 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int md_red_500 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int md_red_600 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int md_red_700 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int md_red_800 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int md_red_900 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int md_red_A100 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int md_red_A200 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int md_red_A400 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int md_red_A700 = 2131034125;
			
			// aapt resource value: 0x7f050071
			public const int md_teal_100 = 2131034225;
			
			// aapt resource value: 0x7f050072
			public const int md_teal_200 = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int md_teal_300 = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int md_teal_400 = 2131034228;
			
			// aapt resource value: 0x7f050070
			public const int md_teal_50 = 2131034224;
			
			// aapt resource value: 0x7f050075
			public const int md_teal_500 = 2131034229;
			
			// aapt resource value: 0x7f050076
			public const int md_teal_600 = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int md_teal_700 = 2131034231;
			
			// aapt resource value: 0x7f050078
			public const int md_teal_800 = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int md_teal_900 = 2131034233;
			
			// aapt resource value: 0x7f05007a
			public const int md_teal_A100 = 2131034234;
			
			// aapt resource value: 0x7f05007b
			public const int md_teal_A200 = 2131034235;
			
			// aapt resource value: 0x7f05007c
			public const int md_teal_A400 = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int md_teal_A700 = 2131034237;
			
			// aapt resource value: 0x7f0500f5
			public const int md_white_1000 = 2131034357;
			
			// aapt resource value: 0x7f0500a9
			public const int md_yellow_100 = 2131034281;
			
			// aapt resource value: 0x7f0500aa
			public const int md_yellow_200 = 2131034282;
			
			// aapt resource value: 0x7f0500ab
			public const int md_yellow_300 = 2131034283;
			
			// aapt resource value: 0x7f0500ac
			public const int md_yellow_400 = 2131034284;
			
			// aapt resource value: 0x7f0500a8
			public const int md_yellow_50 = 2131034280;
			
			// aapt resource value: 0x7f0500ad
			public const int md_yellow_500 = 2131034285;
			
			// aapt resource value: 0x7f0500ae
			public const int md_yellow_600 = 2131034286;
			
			// aapt resource value: 0x7f0500af
			public const int md_yellow_700 = 2131034287;
			
			// aapt resource value: 0x7f0500b0
			public const int md_yellow_800 = 2131034288;
			
			// aapt resource value: 0x7f0500b1
			public const int md_yellow_900 = 2131034289;
			
			// aapt resource value: 0x7f0500b2
			public const int md_yellow_A100 = 2131034290;
			
			// aapt resource value: 0x7f0500b3
			public const int md_yellow_A200 = 2131034291;
			
			// aapt resource value: 0x7f0500b4
			public const int md_yellow_A400 = 2131034292;
			
			// aapt resource value: 0x7f0500b5
			public const int md_yellow_A700 = 2131034293;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int detailFragment = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int detailLayout = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int masterFragment = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int scrollView = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int webView = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DetailFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MasterFragment = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int AppTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
